GET http://localhost:8080/order
Accept: application/json

###
POST http://localhost:8080/order
Accept: application/json
Content-Type: application/json

{
  "orderedAt": "2021-10-06T16:53:27.675931+07:00",
  "customerName": "Test",
  "items":[
    {
      "itemCode": "Item1",
      "description": "ItemDescription",
      "quantity": 1
    },
    {
      "itemCode": "Item2",
      "description": "ItemDescription",
      "quantity": 1
    }
  ]
}

###

PUT http://localhost:8080/order/4
Accept: application/json
Content-Type: application/json

{
  "orderedAt": "2021-10-06T16:53:27.675931+07:00",
  "customerName": "Test update",
  "items":[
    {
      "itemCode": "Item2",
      "description": "ItemDescription",
      "quantity": 1
    },
    {
      "itemCode": "Item2",
      "description": "ItemDescription",
      "quantity": 1
    }
  ]
}

###
GET http://localhost:8080/order/2
Accept: application/json

###


DELETE http://localhost:8080/order/1
Accept: application/json

###