openapi: "3.0.2"
info:
  title: Category RESTful API
  description: This is a sample server Category server.
  version: "1.0"
servers:
  - url: http://localhost:8080/api
    description: Local server
paths:
  /orders:
    post:
      tags:
        - "Order API"
      description: Create New Order
      summary: Create New Order
#      security:
#        - CategoryAuth: []

      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Order"
      responses:
        "200":
          description: Success Create New Order
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    format: int32
                    example: 200
                  status:
                    type: string
                    example: "OK"
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/Order"
    get:
      tags:
        - "Order API"
      description: create a new category
      summary: create a new category
      security:
        - CategoryAuth: []
      responses:
        "200":
          description: Success create a new category
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    format: int32
                    example: 200
                  status:
                    type: string
                    example: "OK"
                  data:
                    $ref: "#/components/schemas/Order"
  /orders/{categoriesId}:
    put:
      tags:
        - "Order API"
      description: Update Order by id
      summary: Update Order by id
      security:
        - CategoryAuth: []
      parameters:
        - name: categoriesId
          in: path
          required: true
          description: ID of category to return
          schema:
            type: integer
            format: int32
            example: 1
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Order"
      responses:
        "200":
          description: Success update Order by id
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    format: int32
                    example: 200
                  status:
                    type: string
                    example: "OK"
                  data:
                    $ref: "#/components/schemas/Order"
    delete:
      tags:
        - "Order API"
      description: Delete Order by id
      summary: Delete Order by id
      security:
        - CategoryAuth: []
      parameters:
        - name: orderId
          in: path
          required: true
          description: ID of Order to return
          schema:
            type: integer
            format: int32
            example: 1
      responses:
        "200":
          description: Success delete category by id
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    format: int32
                    example: 200
                  status:
                    type: string
                    example: "OK"
                  data:
                    type: string
                    example: "Delete category success"

components:
  securitySchemes:
    CategoryAuth:
      type: apiKey
      in: header
      name: X-API-KEY
      description: API Key for Category API
  schemas:
    Item:
      type: object
      properties:
        itemId:
          type: integer
          format: int32
          example: 1
          description: "Item id, needed for update order. When create new order it will be optional"
        itemCode:
          type: integer
          format: int32
          example: 123
        description:
          type: string
          example: "IPhone 12"
        quantity:
          type: integer
          format: int32
          example: 1
    Order:
      type: object
      properties:
        orderId:
          type: integer
          format: int32
          example: 1
          description: "Order id, needed for update order. When create new order it will be optional"
        customerName:
          type: string
          example: "Alex"
        orderedAt:
          type: string
          format: date-time
          example: "2021-01-01T00:00:00Z"
        items:
          type: array
          items:
            $ref: "#/components/schemas/Item"
